# Количество дней бездействия, прежде чем ошибка станет устаревшей
daysUntilStale: 90
# Количество дней бездействия до закрытия устаревшей ошибки
daysUntilClose: 7
# Закрываем только ожидающие ошибки
onlyLabels:
  - status:ожидание
  - type:ошибка
# Метка, используемая при пометке ошибки как устаревшей
staleLabel: status:устарело
# Комментарий к публикации, когда ошибка помечается как устаревшая.
# Установите значение false, чтобы отключить
markComment: >
  Эта ошибка была автоматически помечена как устаревшая, поскольку она не была полностью подтверждена.
  Тикет будет закрыт, если не произойдет никакой дальнейшей активности. Спасибо за ваш вклад ^_^.
# Комментарий к сообщению при закрытии устаревшей ошибки.
# Установите значение false, чтобы отключить
closeComment: false