# Количество дней бездействия, прежде чем ошибка станет устаревшей
daysUntilStale: 90
# Количество дней бездействия до закрытия устаревшей ошибки
daysUntilClose: 7
# Закрываем только ожидающие ошибки
onlyLabels:
  - pending
# Метка, используемая при пометке ошибки как устаревшей
staleLabel: outdated
# Комментарий к публикации, когда ошибка помечается как устаревшая.
# Установите значение false, чтобы отключить
markComment: >
  Это замечание было автоматически помечено как устаревшее, поскольку она не была полностью подтверждена.
  Тикет будет закрыт, если не произойдет никакой дальнейшей активности. Спасибо за Ваш вклад ^_^.
# Комментарий к сообщению при закрытии устаревшей ошибки.
# Установите значение false, чтобы отключить
closeComment: false