name: Задать вопрос
description: Вы можете задать вопрос об интересующих Вас аспектах и механиках.
labels: ['type:вопрос', 'status:ожидание']

body:
  - type: textarea
    attributes:
      label: Развернутое описание Вашего вопроса
      description: Опишите, что конкретно Вы хотели бы уточнить.
    validations:
      required: true